---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: digital advisor, features, upgrade, support offering 
summary: Fournit des informations sur le tableau de bord, les listes de surveillance, les fonctionnalités et les widgets. 
---
= Comprendre les fonctions de Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Grâce à Digital Advisor, vous pouvez consulter l'état général de votre système de stockage, des informations générales sur l'intégrité du système, l'inventaire, la planification, les mises à niveau et de précieuses informations.

Lorsque vous accédez au conseiller numérique pour la première fois, vous pouvez créer une liste de surveillance ou rechercher un nom de client, un nom de site, un nom de groupe, un StorageGRID, un nom d'hôte, Cluster, numéro de série ou ID système.

Vous devez également connaître les couleurs appliquées aux cartes, qui indiquent la gravité et le type de risque.

Voici quelques-unes des fonctionnalités de Digital Advisor :

* Affichez plusieurs listes de suivi, des vues d'informations exploitables et utiles d'un coup d'œil.
* Obtenez des informations sur tous les risques encourus par votre système de stockage et les actions nécessaires pour limiter les risques.
* Limitez les risques grâce à Active IQ Unified Manager.
* Mettez à niveau votre système de stockage.
* Affichez le score de durabilité et l'utilisation projetée de l'énergie, du carbone direct et de la chaleur. Sur la base de ce score, évaluez l'efficacité globale de vos systèmes de stockage et alignez-les sur les actions recommandées par NetApp pour améliorer ce score. link:learn_BlueXP_sustainability.html["En savoir plus >>"^].
* Consultez le taux de réduction des données, l'espace logique utilisé, l'espace physique utilisé et la quantité totale de données sauvegardées pour les systèmes de stockage exécutant ONTAP 9.1 et versions ultérieures.
* Analysez les performances de vos dispositifs de stockage en consultant le format graphique des données de performances.
* Obtenez des informations sur le matériel et les logiciels qui ont expiré ou qui sont sur le point d'expirer au cours des 6 prochains mois.
* Mettez à jour votre firmware ONTAP à l'aide d'Ansible.
* Découvrez les systèmes qui ont dépassé 90 % de capacité ou sont proches de 90 % de capacité.
* Affichez des informations détaillées de configuration physique et logique, notamment un récapitulatif de la configuration du cluster et du nœud, des informations sur le volume et le niveau local, l'interface réseau et les ports, un diagramme qui détaille les disques et les tiroirs disques et quelques visualisations de câbles.
* Fournissez des informations et des informations exploitables sur les différentes piles et utiles pour la résolution de problèmes, l'évaluation des mises à niveau, la validation de la solution et la migration.
* Vérifiez la compatibilité des hôtes et fournissez des recommandations de mise à niveau pour les systèmes d'exploitation hôtes, les pilotes et .
* Obtenez exactement ce que vous voulez trouver de manière plus intelligente et plus rapide.



NOTE: Vous pouvez mettre à niveau l'offre de support à partir du widget *Configuration* du tableau de bord système pour obtenir des informations sur votre base d'installation et bénéficier d'un support personnalisé.
