---
sidebar: sidebar 
permalink: digital-advisor-integration-with-console.html 
keywords: digital advisor, integration, netapp console 
summary: 'Digital Advisor est désormais entièrement intégré à la console NetApp .  Vous pouvez désormais gérer vos clusters et accéder à toutes les fonctionnalités de Digital Advisor depuis l’interface utilisateur (UI) de la console NetApp .' 
---
= Accéder à Digital Advisor dans la console NetApp
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor est désormais entièrement intégré à la console NetApp .  Vous pouvez désormais gérer vos clusters et accéder à toutes les fonctionnalités de Digital Advisor depuis l'interface utilisateur (UI) de la console.

Grâce à la console, les experts informatiques et les architectes cloud peuvent gérer de manière centralisée leur infrastructure multicloud hybride.  Tout ce dont vous avez besoin est un compte NetApp Support Site (NSS) pour accéder à Digital Advisor dans la console.



[[netapp-console]]
== Console NetApp

Digital Advisor est accessible via la console NetApp .

La console NetApp fournit une gestion centralisée des services de stockage et de données NetApp dans les environnements sur site et cloud à l'échelle de l'entreprise.  La console est requise pour accéder aux services de données NetApp et les utiliser.  En tant qu'interface de gestion, il vous permet de gérer de nombreuses ressources de stockage à partir d'une seule interface.  Les administrateurs de console peuvent contrôler l’accès au stockage et aux services pour tous les systèmes de l’entreprise.

Vous n'avez besoin ni de licence ni d'abonnement pour commencer à utiliser NetApp Console et vous n'encourez des frais que lorsque vous devez déployer des agents Console dans votre cloud pour assurer la connectivité à vos systèmes de stockage ou aux services de données NetApp. Cependant, certains services de données NetApp accessibles depuis la Console sont sous licence ou nécessitent un abonnement.

Apprenez-en davantage sur le https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["Console NetApp"].

Vous pouvez accéder à Digital Advisor depuis la console pour gérer votre cluster.

.Étapes
. Ouvrez un navigateur Web et accédez à lalink:https://console.netapp.com/["Console"^] .
. Sélectionnez *Connectez-vous à l'aide de vos informations d'identification du site de support NetApp* et saisissez vos identifiants.
+
Si vous avez déjà créé un identifiant Console à l'aide d'une adresse e-mail et d'un mot de passe, vous devrez continuer à utiliser cette option de connexion.

. Lorsque vous y êtes invité, connectez-vous à l'aide de vos identifiants du site de support NetApp.
+
Cette connexion est différente de celle effectuée à l'étape 2. À l'étape 2, vous vous êtes connecté à la NetApp Console. Vous vous connectez maintenant à Digital Advisor.



*Résultat*

Toutes vos listes de surveillance et configurations existantes s'affichent et vous pouvez désormais utiliser Digital Advisor comme vous le faites habituellement.
