---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'Digital Advisor (anciennement Active IQ Digital Advisor) est désormais entièrement intégré à BlueXP. Vous pouvez désormais gérer vos clusters et accéder à toutes les fonctionnalités de Digital Advisor à partir de l"interface utilisateur BlueXP.' 
---
= Intégration de Digital Advisor avec BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor (anciennement Active IQ Digital Advisor) est désormais entièrement intégré à BlueXP. Vous pouvez désormais gérer vos clusters et accéder à toutes les fonctionnalités de Digital Advisor à partir de l'interface utilisateur BlueXP.

BlueXP permet aux experts IT et aux architectes cloud de gérer de manière centralisée leur infrastructure multicloud hybride. Il vous suffit d'un compte sur le site de support NetApp pour accéder au conseiller digital dans BlueXP.



== Présentation de l'intégration

À partir de novembre 2022, les utilisateurs de Digital Advisor seront encouragés à utiliser Digital Advisor dans BlueXP. Depuis BlueXP, vous aurez accès à la même interface de Digital Advisor que celle à laquelle vous êtes habitué, et plus encore. BlueXP vous permet de créer et de gérer le stockage cloud (par exemple Cloud Volumes ONTAP), d'utiliser les services de données NetApp (par exemple, Cloud Backup) et de contrôler de nombreux périphériques de stockage sur site et à la périphérie.



== Accès à Digital Advisor dans BlueXP

Vous pouvez accéder à Digital Advisor à partir de BlueXP pour gérer votre cluster.

.Étapes
. Ouvrez un navigateur Web et accédez à https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^]
. Sélectionnez *Connectez-vous à l'aide de vos informations d'identification du site de support NetApp* et saisissez vos identifiants.
+
Si vous avez déjà créé une connexion BlueXP à l'aide d'un e-mail et d'un mot de passe, vous devrez continuer à utiliser cette option de connexion.

. Lorsque vous y êtes invité, connectez-vous à l'aide de vos identifiants du site de support NetApp.
+
Cette connexion est différente de la connexion effectuée à l'étape 2. À l'étape 2, vous vous êtes connecté à la plate-forme BlueXP. Vous vous connectez maintenant à Digital Advisor.



*Résultat*

Toutes vos listes de surveillance et configurations existantes s'affichent et vous pouvez désormais utiliser Digital Advisor comme vous le faites habituellement.



== En savoir plus sur BlueXP

https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["Pour en savoir plus, consultez la documentation BlueXP"^]
