---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP, NetApp Console 
summary: 'Fournit des informations sur le développement durable qui vous permettent de réduire la consommation d"énergie et de travailler à la réalisation de vos objectifs environnementaux.' 
---
= En savoir plus sur le développement durable
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La durabilité vous permet de réduire la consommation d’énergie et vous permet de travailler vers vos objectifs environnementaux.  Cela vous permet d’aligner vos systèmes de stockage sur des pratiques respectueuses de l’environnement et d’atteindre les objectifs de durabilité.

Vous pouvez consulter le score de durabilité et l'utilisation prévue de l'énergie, du carbone direct et de la chaleur à partir du tableau de bord de durabilité.  Vous pouvez ajuster le pourcentage d’atténuation du carbone pour des sites spécifiques.  Vous pouvez également consulter le score de durabilité au niveau du cluster.  En fonction du score de durabilité, vous pouvez évaluer la posture de durabilité et mettre en œuvre les actions recommandées par NetApp pour améliorer le score.  Pour en savoir plus sur le tableau de bord de durabilité, rendez-vous surlink:sustainability-dashboard-overview.html["Présentation du tableau de bord Sustainability"] .


NOTE: Le développement durable est pris en charge par les systèmes Cloud Volumes ONTAP, AFF (A-Series et C-Series), E-Series, FAS et StorageGRID.

Vous pouvez visionner la vidéo suivante pour comprendre le tableau de bord Sustainability :

video::yNRHeOvbGX8[youtube,width=848,height=480]


== Avantages de la durabilité

Le développement durable offre les avantages suivants :

* Accélérer les performances en réduisant le nombre de dispositifs de stockage pour stocker le même volume de données.
* Réduisez les coûts de stockage en optimisant l'utilisation des systèmes de stockage.
* Réduction de l'empreinte carbone grâce à l'utilisation d'énergie renouvelable dans les data centers
* Améliorer l'efficacité énergétique en mettant en œuvre des politiques d'efficacité énergétique.

