---
settings:
  name: Digital Advisor
  release_notes_autogen:
    release_notes_repo: console-relnotes
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents Digital Advisor
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/reference_new_activeiq.html"
    - title: Limites connues
      url: "/reference_limitations_activeiq.html"
  - title: Commencez
    entries:
    - title: Démarrage rapide de Digital Advisor
      url: "/concept_getting_started_2.html"
    - title: Découvrez les fonctionnalités de Digital Advisor
      url: "/concept_understand_activeiq_features.html"
    - title: Accéder à Digital Advisor dans la console NetApp
      url: "/digital-advisor-integration-with-console.html"
    - title: En savoir plus sur Digital Advisor
      url: "/concept_key_terms.html"
    - title: Découvrez AutoSupport
      url: "/concept_autosupport.html"
    - title: Connectez-vous à Digital Advisor
      url: "/task_login_activeiq.html"
    - title: Liste de surveillance des provisions
      entries:
      - title: Découvrez les listes de surveillance
        url: "/concept_overview_dashboard.html"
      - title: Créer une liste de surveillance
        url: "/task_add_watchlist.html"
      - title: Gérer une liste de surveillance
        url: "/task_manage_watchlists.html"
    - title: FAQ pour Digital Advisor
      url: reference_aiq_faq.html
  - title: Utiliser Digital Advisor
    entries:
    - title: Analyser les attributs bien-être
      entries:
      - title: Découvrez le widget bien-être
        url: "/concept_overview_wellness.html"
      - title: Identifier les risques liés au système de stockage et prendre des mesures
          correctives
        url: "/task_view_risk_and_take_action.html"
      - title: Détecter les risques de sécurité et prendre des mesures correctives
        url: "/task_increase_protection_against_hackers_and_Ransomware_attacks.html"
      - title: Protégez vos systèmes de stockage contre les risques liés aux ransomwares.
        url: "/task_protect_systems_against_ransomware_risks.html"
      - title: Analyser les attributs de bien-être et reconnaître les risques
        url: "/task_view_and_acknowledge_risks.html"
      - title: Consulter l'historique des risques du système de stockage
        url: "/task_view_wellness_history.html"
      - title: Visualisez et atténuez les risques à l'aide d'Unified Manager ou d'un
          playbook Ansible.
        url: "/task_view_risks_remediated_unified_manager.html"
      - title: Utilisez Digital Advisor pour corriger les risques critiques identifiés
        url: "/task_avoid_the_downtime_and_possible_data_loss.html"
      - title: Abonnez-vous aux notifications d'état du système de stockage
        url: "/task_subscribe_to_wellness_review_email.html"
      - title: Identifier les renouvellements logiciels et matériels du système de
          stockage
        url: "/task_renew_software_and_hardware.html"
      - title: Visualisez l'état des clusters et des nœuds à l'aide du widget ClusterViewer
        url: "/task_analyze_wellness_clusters_and_nodes.html"
    - title: Analyser la durabilité du système de stockage
      entries:
      - title: En savoir plus sur le développement durable
        url: "/learn-about-sustainability.html"
      - title: Accédez au tableau de bord de durabilité
        url: "/get_started_sustainability_dashboard.html"
      - title: Découvrez les fonctionnalités du tableau de bord de développement durable
        url: "/sustainability-dashboard-overview.html"
      - title: Améliorer le score de durabilité du système de stockage
        url: "/improve_sustainability_score.html"
    - title: Générer un plan de mise à niveau
      entries:
      - title: Découvrez comment générer un plan de mise à niveau ONTAP
        url: "/upgrade_advisor_overview.html"
      - title: Générer un plan de mise à niveau ONTAP pour un ou plusieurs clusters
        url: "/generate_upgrade_plan_single_multiple_clusters.html"
      - title: Affichez les recommandations de mise à jour du firmware
        url: "/view-firmware-update-recommendations.html"
    - title: Afficher les détails du système
      entries:
      - title: Consulter les détails de l'inventaire du système de stockage
        url: "/task_view_inventory_details.html"
      - title: Consultez les données des machines virtuelles disponibles dans Data
          Infrastructure Insights.
        url: "/task-integrating-with-cloud-insights-to-view-vm-details.html"
      - title: Consultez les demandes d'assistance et les détails du système de stockage
          grâce au widget « Informations précieuses ».
        url: "/task_view_valuable_insight_widget.html"
      - title: Consultez l'utilisation de la capacité avec l'abonnement NetApp Keystone
        url: "/view_keystone_capacity_utilization.html"
    - title: Identifiez de manière proactive la configuration système requise
      entries:
      - title: Gérez les besoins en capacité du système de stockage avec le widget
          de planification
        url: "/concept_overview_planning.html"
      - title: Identifier les systèmes de stockage qui approchent de leurs limites
          de capacité
        url: "/task_identify_capacity_system.html"
      - title: Gérer les seuils de capacité de stockage de volume
        url: "/task_avoid_a_volume_filling_up_to_prevent_an_outage.html"
      - title: Déterminer si une mise à niveau technologique est recommandée pour
          le système de stockage
        url: "/evaluate-tech-refresh.html"
      - title: Renouveler les logiciels et le matériel du système de stockage
        url: "/task_renew_software_and_hardware.html"
    - title: Analysez l'état de votre système de stockage grâce aux recommandations
        cloud.
      url: "/task-informed-decisions-based-on-cloud-recommendations.html"
    - title: Identifiez les écarts de configuration
      entries:
      - title: Détecter les écarts de configuration du système de stockage
        url: "/concept_overview_config_drift.html"
      - title: Ajouter un modèle de dérive de configuration pour le système de stockage
        url: "/task_add_config_drift_template.html"
      - title: Comparer les modèles de dérive de configuration
        url: "/task_compare_config_drift_template.html"
      - title: Générer un rapport chronologique de dérive de configuration
        url: "/task_generate_drift_timeline_report.html"
      - title: Gérer les modèles de dérive de configuration
        url: "/task_manage_template.html"
    - title: Améliorer l'efficacité et les performances du système de stockage
      entries:
      - title: Économies de capacité et d'efficacité de stockage
        url: "/task_analyze_storage_efficiency.html"
      - title: Afficher les graphiques de performance du système de stockage
        url: "/task_view_performance_graphs.html"
    - title: Analyser l'état du système de stockage
      entries:
      - title: Découvrez le tableau de bord de contrôle de santé
        url: "/concept_understand_health_check_dashboard.html"
      - title: Lancez-vous avec le tableau de bord Health Check
        url: "/concept_get_started_with_health_check_dashboard.html"
      - title: Renouveler les contrats de soutien
        url: "/task_renew_support_contracts_for_your_systems.html"
    - title: Mettez à niveau pour optimiser votre base installée
      entries:
      - title: Offre de support de mise à niveau
        url: "/task_upgrade_support_offering.html"
      - title: Mise à jour du firmware AFF et FAS à l'aide d'un playbook Ansible
        entries:
        - title: Téléchargez le package Ansible du firmware AFF et FAS
          url: "/task_update_AFF_FAS_firmware.html"
        - title: Mise à jour du firmware AFF et FAS à l'aide d'un package Ansible
            (utilisateurs expérimentés)
          url: "/task_install_execute_firmware_update_exp_user.html"
        - title: Installation et exécution du firmware AFF et FAS, package d'automatisation
            Ansible (débutants)
          entries:
          - title: Hébergez les fichiers de firmware AFF et FAS sur un serveur web
            url: "/task_hosting_firmware_files_using_web_server.html"
          - title: Mettez à jour le fichier d'inventaire pour la mise à jour du firmware
              AFF et FAS
            url: "/concept_working_with_inventory_file.html"
          - title: Exécutez le playbook Ansible à l'aide de l'image Docker NetApp.
            url: "/task_execute_ansible_playbook_using_docker.html"
          - title: Exécutez le playbook Ansible sans l'image Docker NetApp.
            url: "/task_execute_ansible_playbook_without_docker.html"
          - title: Validez l'installation du firmware AFF et FAS sur le système de
              stockage.
            url: "/task_validate_firmware_installation.html"
    - title: Intégrez les données à l'aide d'API
      entries:
      - title: Découvrez les services API de Digital Advisor
        url: "/concept_overview_API_service.html"
      - title: Générez des jetons pour utiliser les services de l'API Digital Advisor
        url: "/task_generate_tokens_API_services.html"
      - title: Utilisez le catalogue d'API Digital Advisor pour exécuter les API.
        url: "/task_view_API_catalog.html"
    - title: Générer des rapports personnalisés
      entries:
      - title: Découvrez les rapports de Digital Advisor
        url: "/concept_report_types.html"
      - title: Générer ou programmer un rapport
        url: "/task_generate_reports.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/reference_ansible_troubleshoot_feedback_support.html"
    - title: Obtenez de l'aide
      url: "/concept_get_more_information.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
