---
sidebar: sidebar 
permalink: reference_limitations_activeiq.html 
keywords: limitation, issues, not supported, drawbacks 
summary: Fournit des informations sur les limites dans la version. 
---
= Limites connues
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.

Les limites suivantes existent :

* Pour les systèmes de stockage Data ONTAP 7-mode uniquement (les systèmes de stockage Data ONTAP 7-mode approchent de la fin de leur support)
+
** Graphiques de performances
** Efficacité du stockage


* Upgrade Advisor ne prendra pas en charge les plans de mise à niveau pour clustered ONTAP avant la version 9.0.




== La modification d'une liste de surveillance peut prendre 60 minutes pour réfléchir dans Digital Advisor

La modification d'une liste de surveillance ne met pas immédiatement à jour les informations dans Digital Advisor. La réflexion des modifications dans Digital Advisor peut prendre jusqu'à 60 minutes.



== Un rapport vierge s'affiche pendant la planification des rapports

Les rapports programmés sont disponibles uniquement avec un contrat de support SupportEdge Advisor ou SupportEdge Expert. Si vos systèmes ne sont pas soumis à SupportEdge Advisor ou à un contrat de support SupportEdge Expert, vous risquez d'obtenir un rapport vierge lors de la planification des rapports.



== Le conseiller numérique peut prendre 60 minutes pour réfléchir aux risques reconnus et non reconnus

L'état des risques qui sont reconnus et non reconnus ne reflète pas immédiatement dans Digital Advisor. Il peut s'avérer nécessaire de prendre jusqu'à 60 minutes pour que les changements soient pris en compte dans Digital Advisor et dans le rapport de bien-être.



== Widget AutoSupport non disponible pour le cluster et les numéros de série

Le widget AutoSupport ne fournit pas d'alertes pour la recherche de clusters et de numéros de série.



== Le widget AutoSupport ne peut pas accéder aux détails AutoSupport du niveau série

Sur la page Rapports AutoSupport, cliquez sur l'un des États, les systèmes qui ont récemment cessé d'envoyer ou les systèmes sur lesquels AutoSupport est désactivé pour accéder à l'écran Vérification de l'état.



== Le filtrage et le tri ne sont pas disponibles dans le widget Inventaire

Vous ne pouvez pas filtrer et trier les données dans le widget d'inventaire. Aucune donnée n'est affichée si vous sélectionnez ONTAP AFF, ONTAP ASA, ONTAP Edge ou ONTAP Select dans la liste déroulante « Filtrer par ».
