---
sidebar: sidebar 
permalink: task_view_API_catalog.html 
keywords: API Catalog, APIs, integrate data, view catalog 
summary: 'Fournit des informations sur les API disponibles dans le catalogue d"API.' 
---
= Utilisez le catalogue d'API pour exécuter les API
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le catalogue d'API vous permet de parcourir les catégories et les API disponibles dans chacune de ces catégories.

À l'aide d'un jeton d'accès valide et des entrées correctes pour les champs requis, vous pouvez effectuer un appel de test pour une API.



== Accéder aux API GraphQL

.Étapes
. Dans le menu *Quick Links*, cliquez sur *API Services*.
. Cliquezlink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Parcourir"] sous l'icône *Catalogue API*.
+
Le catalogue API s'affiche.

. Cliquez sur *GraphQL* et consultez la documentation.
. Essayez les API GraphQL en utilisant les exemples de requêtes prêts à l'emploi surlink:https://studio.apollographql.com/public/ActiveIQ-Graph-Prd-API/variant/current/explorer?collectionId=251c50ce-797e-4549-bb9c-f6557ef5a176OPERATION_COLLECTIONfocusCollectionId=251c50ce-797e-4549-bb9c-f6557ef5a176["Digital Advisor GraphQL Studio"^] .
. Fournissez un jeton utilisateur en sélectionnant le champ d'autorisation dans l'en-tête de la demande d'API
. Fournir les variables requises
. Exécutez la requête et examinez le résultat




== Accéder aux API REST

.Étapes
. Dans le menu *Quick Links*, cliquez sur *API Services*.
. Cliquezlink:https://activeiq.netapp.com/catalog/internal/api-reference/introduction["Parcourir"] sous l'icône *Catalogue API*.
+
Le catalogue API s'affiche.

. Cliquez sur *ActiveIQ-Public* et sélectionnez n'importe quelle API
. En haut de la page, faites glisser le commutateur sur « expérience ».
. Dans le menu de navigation de gauche, développez les catégories et sélectionnez n'importe quelle API pour afficher des informations détaillées.
. Développez l'API.
. Cliquez sur le bouton *essayez-le* à droite.
. Indiquez les paramètres requis et cliquez sur *Exécuter* pour afficher les résultats.
+
Vous pouvez aussi examiner la section *réponses* de l'API pour comprendre les données qui seront mieux renvoyées. Vous pouvez cliquer sur *exemple valeur* pour afficher le format des données ou cliquer sur *modèle* et cliquer sur les carts pour développer les sections afin de voir la définition de chaque élément.



En faisant glisser le curseur sur la vue *Code*, vous pouvez afficher les échantillons de code dans différentes langues.
