---
sidebar: sidebar 
permalink: task_login_activeiq.html 
keywords: login, log in 
summary: Fournit des informations pour se connecter à Digital Advisor. 
---
= Connectez-vous à Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez vous connecter à Digital Advisor à partir d'une console web pour afficher l'état global de votre système de stockage.

.Avant de commencer
Vous devez disposer d'informations d'identification valides sur le site de support NetApp pour vous connecter à Digital Advisor. Si vous ne possédez pas de compte et que vous commencez, consultez l'article suivant de la base de connaissances pour créer un compte :
link:https://kb.netapp.com/Support/General_Support/How_to_register_for_a_NetApp_Support_Site_account_as_a_Customer_or_a_Guest_user["Comment vous inscrire en tant que client ou utilisateur invité sur le site de support NetApp"^].

.Étapes
. Accédez au link:https://activeiq.netapp.com/?source=onlinedocs["Conseiller digital"^] page de connexion.
+
Digital Advisor affiche les systèmes disposant d'un contrat de support valide. Si le contrat expire, une période de grâce de 90 jours est accordée pour que les systèmes restent visibles. Par la suite, les systèmes ne sont ni consultables ni visibles au sein de Digital Advisor.

. Indiquez votre nom d'utilisateur et votre mot de passe, puis cliquez sur *connexion*.

