---
sidebar: sidebar 
permalink: task_view_risk_and_take_action.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, mitigate, rectify 
summary: Fournit des informations pour afficher et analyser le bien-être de votre système de stockage et réduire les risques. 
---
= Consultez les risques liés au système de stockage dans Digital Advisor et prenez les mesures correctives nécessaires.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez analyser les attributs d'intégrité de votre système de stockage en visualisant les actions et les risques associés. Vous devez afficher les actions correctives associées et réduire manuellement le risque.

.Étapes
. Sélectionnez le widget *Bien-être* sur le tableau de bord ou sélectionnez *Afficher toutes les actions* pour consulter la liste de toutes les actions et risques.
. Afficher les *actions* et *risques* associés à l'attribut bien-être.
. Sélectionnez *Actions* pour afficher les risques associés aux actions, sélectionnez *Risques* pour afficher tous les risques, ou sélectionnez *Systèmes affectés* pour afficher les systèmes qui nécessitent une attention.
. Sélectionnez le nom du risque pour afficher des informations sur le risque.
. Sélectionnez les actions correctives associées et suivez les instructions pour résoudre le risque.


Les étapes permettant de réduire les risques sont les mêmes pour tous les attributs de bien-être. Vous pouvez visionner la vidéo suivante pour surveiller et résoudre les problèmes de sécurité :

video::ssXI-FAKMis[youtube,width=848,height=480]