---
sidebar: sidebar 
permalink: task_protect_systems_against_ransomware_risks.html 
keywords: ransomware, risks, ransomware risks 
summary:  
---
= Protégez les systèmes de stockage gérés par Digital Advisor contre les risques de ransomware.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous vous connectez à Digital Advisor, vous pouvez afficher les *actions* mises en surbrillance dans le widget *sécurité et défense anti-ransomware*, qui affiche le nombre de risques.

Vous pouvez consulter les risques liés à la création, à la conservation et à la stratégie ONTAP FPolicy des instantanés, puis prendre des mesures pour les corriger.

.Étapes
. Connectez-vous à Digital Advisor.
. Sélectionnez *Actions* sur le widget *Security & Ransomware Defense*.
. Décochez la case *vulnérabilités de sécurité*.
. Pour les risques affichés, vérifiez le niveau d'impact et suivez les actions recommandées.
. Sélectionnez l'onglet *Risques uniques* et sélectionnez le lien dans la colonne *Mesures correctives*.
. Sélectionnez l'onglet *Systèmes concernés* pour afficher les systèmes présentant des risques.
. Sélectionnez les mesures correctives recommandées pour protéger les systèmes.

