---
sidebar: sidebar 
permalink: task_view_and_acknowledge_risks.html 
keywords: wellness, performance, efficiency, availability, capacity, security vulnerabilities, protection, protect, acknowledge, unacknowledge, disregard 
summary: Fournit des informations pour afficher et analyser le bien-être de votre système de stockage et prendre en compte les risques. 
---
= Analysez les attributs de bien-être dans Digital Advisor et prenez en compte les risques.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez analyser les attributs d'intégrité de votre système de stockage en visualisant les actions et les risques associés. Vous devez afficher les actions correctives et réduire manuellement le risque.

.Étapes
. Sélectionnez le widget d'attribut de bien-être sur le tableau de bord ou sélectionnez *Afficher toutes les actions* pour consulter la liste de toutes les actions et des risques.
. Afficher les *actions* et *risques* associés à l'attribut bien-être.
. Sélectionnez *Actions* pour afficher les risques associés aux actions, sélectionnez *Risques* pour afficher tous les risques, ou sélectionnez *Systèmes affectés* pour afficher les systèmes qui nécessitent une attention.
. Sélectionnez le risque pour afficher le résumé du risque.
. Sélectionnez *Ack* pour reconnaître le risque.
+
Les informations récapitulatives détaillées des risques ainsi que les actions correctives à mettre en œuvre manuellement afin de limiter les risques sont disponibles.

. Si vous ne souhaitez pas ou n'êtes pas en mesure d'atténuer le risque pour le moment, fournissez les valeurs des champs et sélectionnez *Accuser réception*.
+
Le risque sera ajouté aux risques reconnus.




NOTE: Si vous ne souhaitez plus qu'un risque soit reconnu, vous pouvez ignorer le risque en sélectionnant *Annuler la prise en compte* et en suivant les mêmes étapes.
