---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ONTAP systems, StorageGRID 
summary: Fournit des informations pour augmenter la capacité du système. 
---
= Identifier les systèmes qui atteignent les limites de capacité
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifiez de manière proactive les systèmes qui atteignent les limites de capacité et envoyez une demande d'augmentation de la capacité de votre système de stockage.

Pour ONTAP, vous pouvez afficher les systèmes qui ont dépassé 90 % de capacité ou qui doivent dépasser 90 % de capacité en 1, 3 et 6 mois. Pour StorageGRID, vous pouvez afficher les systèmes qui ont dépassé 70 % de capacité ou qui doivent dépasser 70 % de capacité en 1, 3 et 6 mois.

.Étapes
. Dans le widget *Planning*, cliquez sur *Capacity additions*.
+
Par défaut, les systèmes ONTAP qui ont dépassé 90 % de capacité ou sont proches de 90 % de capacité sont affichés.

. Cliquez sur l'onglet *StorageGRID* pour afficher les systèmes StorageGRID dont la capacité dépasse 70 % ou qui approchent 70 %.
. Sélectionnez les systèmes pour lesquels vous souhaitez augmenter la capacité.
. Cliquez sur *Afficher la prévision de capacité* pour afficher la prévision de capacité pour les 6 prochains mois.
. Cliquez sur *demande d'ajout de capacité*.
. Si vous le souhaitez, ajoutez des commentaires.
. Cliquez sur *Envoyer* pour envoyer la demande à l'équipe de stockage NetApp afin de l'aider à ajouter de la capacité pour les systèmes sélectionnés.

