---
sidebar: sidebar 
permalink: task_generate_reports.html 
keywords: reports, generate reports 
summary: Fournit des informations pour générer des rapports. 
---
= Générez ou planifiez un rapport dans Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez générer des rapports immédiatement ou planifier la génération d'un rapport toutes les semaines ou tous les mois. Les rapports peuvent être générés dans différents formats. En fonction du rapport sélectionné, les formats disponibles sont affichés.

*À propos de cette tâche*

* Vous ne pouvez pas modifier les rapports dans Digital Advisor. Vous devez supprimer le rapport existant et créer un nouveau rapport.


.Étapes
. Dans le volet de gauche, sélectionnez *Rapports*.
. Sélectionnez *Créer un rapport* pour générer un nouveau rapport.
+
Vous pouvez générer un rapport immédiatement ou planifier la génération du rapport sur une base hebdomadaire ou mensuelle.



[cols="50,50"]
|===
| Pour générer un rapport immédiatement | Pour planifier la génération du rapport sur une base hebdomadaire ou mensuelle 


 a| 
. Sélectionnez le type de rapport et fournissez les valeurs requises pour le rapport.
. Sélectionnez le format du rapport.
. Sélectionnez *Soumettre*.



NOTE: Le rapport est enregistré dans Digital Advisor pendant 3 mois.
 a| 
. Sélectionnez l'onglet *Schedule Report*.
. Sélectionnez le type de rapport et fournissez les valeurs requises pour le rapport.
. Sélectionnez le format du rapport.
. Sélectionnez la fréquence du rapport.
. Sélectionnez la date de début et la date de fin du rapport.
. Sélectionnez *Soumettre*.



NOTE: Les rapports planifiés existants seront remplacés lors de la génération des nouveaux rapports.

|===