---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Abonnez-vous aux notifications de santé de votre système de stockage auprès de Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez vous abonner à la newsletter de bilan de santé pour recevoir un e-mail mensuel récapitulant l'état de santé des systèmes de stockage, les systèmes de stockage dont la date de renouvellement approche et les systèmes de stockage nécessitant une mise à niveau pour les produits NetApp de votre parc installé. Vous recevrez un courriel de bilan de santé vous permettant de consulter un résumé mensuel et de prendre les mesures nécessaires pour vos systèmes de stockage. Vous avez également la possibilité de consulter, modifier, partager et supprimer vos abonnements. À tout moment, si vous décidez de ne plus recevoir ces courriels, vous pouvez vous désabonner.

Une fois l'abonnement activé, vous devez sélectionner une date de début lors de l'ajout d'un abonnement. Chaque mois, le résumé de l'e-mail vous offre une vue d'ensemble des actions de bien-être, de renouvellement, de mise à niveau et de vérification de l'état de santé exceptionnelles. Vous pouvez confirmer l'adresse e-mail et l'adresse e-mail est envoyée à l'adresse e-mail spécifiée. Vous avez également la possibilité de supprimer des abonnements.


NOTE: Cette fonctionnalité n'est disponible que dans les offres de services NetApp SupportEdge Advisor et SupportEdge Expert.

.Étapes
. Dans le volet de gauche, cliquez sur *Wellness Review*.
. Cliquez sur *Ajouter un abonnement*.
. Indiquez les informations requises dans les champs *Nom de l'abonnement*, *choisir Catégorie*, *Rechercher client* et *Email* de la boîte de dialogue *Ajouter un nouvel abonnement*.
. Cliquez sur *Subscribe*.
+
Une fois l'abonnement réussi, vous recevrez un message *l'abonnement a été ajouté*.


