---
sidebar: sidebar 
permalink: task_validate_firmware_installation.html 
keywords: validate, firmware, firmware installation 
summary: 'Le fournit des informations sur la validation de l"installation du micrologiciel.' 
---
= Validation de l'installation du firmware
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Après l'exécution du PlayBook, connectez-vous au cluster en tant qu'administrateur du cluster.



== Validation de l'installation du firmware du disque

.Étapes
. Vérifiez que le micrologiciel du lecteur est installé :
+
[listing]
----
::*> storage disk show -fields firmware-revision,model
disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----
+
Pour plus d'informations sur la commande, reportez-vous à {LINK-with-soulignements}[Storage disk show].

. Vérifiez que le nouveau firmware NVMe Flash cache est installé :
+
[listing]
----
::*> system controller flash-cache show
----
+
Pour plus d'informations sur la commande, reportez-vous à {LINK-with-soulignements}[system Controller Flash cache show].





== Validez l'installation du firmware du tiroir

.Étapes
. Vérifiez que le nouveau firmware du tiroir est mis à jour :
+
[listing]
----
::*> system node run -node * -command sysconfig -v
----
+
Dans le résultat de la commande, vérifiez que le firmware de chaque tiroir est mis à jour au niveau souhaité. Par exemple :

+
[listing]
----
Shelf 1: IOM6 Firmware rev. IOM6 A: 0191 IOM3 B: 0191
----
+
Pour plus d'informations sur la commande, reportez-vous à {LINK-with-soulignements}[system node run].

. Vérifier que le nouveau firmware ACP est mis à jour :
+
[listing]
----
::*> storage shelf acp module show -instance
----
+
Pour plus d'informations sur la commande, reportez-vous à {LINK-with-soulignements}[Storage shelf acp module show].

. Vérifiez que le mode ACP souhaité est configuré :
+
[listing]
----
::*> storage shelf acp show
----
+
Pour plus d'informations sur la commande, reportez-vous à {LINK-with-soulignements}[Storage tiroir acp show].

. Modifiez le mode ACP (canal) :
+
[listing]
----
::*> storage shelf acp configure -channel [in-band | out-of-band]
----
+
Pour plus d'informations sur la commande, reportez-vous à {link-with-soulignements}[configuration acp du tiroir de stockage].





== Validation de l'installation du micrologiciel SP/BMC

Les mises à jour du firmware Ansible PlayBook pour le processeur de service/BMC sont activées avec une option permettant de vérifier l'installation du dernier firmware SP/BMC sur le contrôleur. Une fois la vérification terminée (les mises à jour peuvent prendre une durée maximale de deux heures), Ansible PlayBook applique les mises à jour internes du firmware des commutateurs en se connectant à la console SP/BMC.

Les informations de défaillance et de réussite du micrologiciel SP/BMC et des installations de firmware du commutateur interne seront notifiées à la fin de l'exécution d'Ansible PlayBook. Suivez les étapes indiquées dans le manuel Ansible PlayBook si l'installation du firmware du commutateur interne/du micrologiciel du processeur de service/BMC/du commutateur interne échoue.
