---
sidebar: sidebar 
permalink: task_identify_capacity_system.html 
keywords: capacity, space, increase, ontap systems, storagegrid, storage expansion 
summary: Fournit des informations pour augmenter la capacité du système. 
---
= Identifiez les systèmes de stockage proches de leurs limites de capacité dans Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Identifiez de manière proactive les systèmes qui atteignent les limites de capacité et envoyez une demande d'augmentation de la capacité de votre système de stockage.

Pour ONTAP, vous pouvez afficher les systèmes qui ont dépassé 90 % de capacité ou qui doivent dépasser 90 % de capacité en 1, 3 et 6 mois. Pour StorageGRID, vous pouvez afficher les systèmes qui ont dépassé 70 % de capacité ou qui doivent dépasser 70 % de capacité en 1, 3 et 6 mois.

.Étapes
. Dans le widget *Planification*, sélectionnez *Extension de stockage*.
+
Par défaut, les systèmes ONTAP qui ont dépassé 90 % de capacité ou sont proches de 90 % de capacité sont affichés.

. Sélectionnez l’onglet *StorageGRID* pour afficher les systèmes StorageGRID qui ont dépassé 70 % de leur capacité ou qui approchent de 70 % de leur capacité.
. Sélectionnez les systèmes pour lesquels vous souhaitez augmenter la capacité.
. Sélectionnez *Afficher les prévisions de capacité* pour consulter les prévisions de capacité pour les 6 prochains mois.
. Sélectionnez *Demande d'ajout de capacité*.
. Si vous le souhaitez, ajoutez des commentaires.
. Sélectionnez *Envoyer* pour envoyer la demande à l’équipe de stockage NetApp afin d’obtenir de l’aide pour l’extension du stockage des systèmes sélectionnés.

