---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Abonnez-vous aux notifications de santé de votre système de stockage auprès de Digital Advisor.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: La fonctionnalité « Bilan bien-être » a été supprimée et n'est plus disponible dans Digital Advisor depuis juillet 2026.

Vous pouvez vous abonner à l’e-mail de bilan santé pour recevoir chaque mois un e-mail qui résume l’état de santé, les systèmes de stockage approchant de leur date de renouvellement, ainsi que les systèmes de stockage nécessitant une mise à niveau pour les produits NetApp de votre base installée. Vous recevrez un e-mail de bilan santé afin de pouvoir consulter un résumé mensuel et prendre des mesures pour vos systèmes de stockage.

Vous pouvez également consulter, modifier, partager et supprimer vos abonnements. À tout moment, si vous décidez de ne plus recevoir les e-mails, vous pouvez également vous désabonner de la réception des e-mails.

Une fois l'abonnement activé, vous devez sélectionner une date de début lors de l'ajout d'un abonnement. Chaque mois, le résumé de l'e-mail vous offre une vue d'ensemble des actions de bien-être, de renouvellement, de mise à niveau et de vérification de l'état de santé exceptionnelles. Vous pouvez confirmer l'adresse e-mail et l'adresse e-mail est envoyée à l'adresse e-mail spécifiée. Vous avez également la possibilité de supprimer des abonnements.


NOTE: Cette fonctionnalité n'est disponible que dans les offres de services NetApp SupportEdge Advisor et SupportEdge Expert.

.Étapes
. Dans le volet de gauche, cliquez sur *Wellness Review*.
. Cliquez sur *Ajouter un abonnement*.
. Indiquez les informations requises dans les champs *Nom de l'abonnement*, *choisir Catégorie*, *Rechercher client* et *Email* de la boîte de dialogue *Ajouter un nouvel abonnement*.
. Cliquez sur *Subscribe*.
+
Une fois l'abonnement réussi, vous recevrez un message *l'abonnement a été ajouté*.


