---
sidebar: sidebar 
permalink: task-integrating-with-cloud-insights-to-view-vm-details.html 
keywords: Cloud Insights, VMs, virtual machines, Data Infrastructure Insights 
summary: Fournit des informations sur les machines virtuelles dans Data Infrastructure Insights 
---
= Intégration avec Data Infrastructure Insights pour afficher les détails des machines virtuelles
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor est désormais intégré à la version Data Infrastructure Insights Basic pour fournir un inventaire complet de la pile et des contrôles d'interopérabilité aux clients.

Les avantages de cette intégration sont les suivants :

* Surveillance SaaS simplifiée de ONTAP
* Visibilité sur la surveillance de l'ensemble de la pile VMware
* Les clients réalisent des économies en termes de productivité grâce à des vérifications automatisées de l'interopérabilité pour faciliter la planification des mises à niveau ONTAP. Résultat : des mises à niveau plus fluides des ONTAP et des risques d'incompatibilité avec les hôtes.



NOTE: Cette fonctionnalité est disponible uniquement pour les contrats de mise à niveau SupportEdge Advisor, SupportEdge Expert et Digital Advisor.

.Étapes
. Dans le widget *Inventaire*, cliquez sur *Machines virtuelles* pour afficher les données disponibles dans Data Infrastructure Insights.
. Cliquez sur l'onglet *vue d'ensemble de la machine virtuelle*.
. Cliquez sur *nombre d'hôtes ESX* pour afficher des informations sur l'hôte.
. Cliquez sur le *Nom ESX* pour accéder à Data Infrastructure Insights et afficher plus d’informations.

