---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: 'Fournit des informations sur l"inventaire global que vous possédez.' 
---
= Consultez les détails de votre inventaire de système de stockage dans Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le widget *Inventaire* vous fournit un aperçu de l'ensemble des systèmes et des commutateurs bénéficiant d'un support que vous possédez.  Cela inclut les produits compatibles et non compatibles avec Digital Advisor .

Vous pouvez également générer le rapport de la liste de surveillance sélectionnée et envoyer le rapport par e-mail à un maximum de 5 destinataires.

video::ttbpbT5uTBI[youtube,width=848,height=480]


[[view-system-details]]
== Afficher les détails du système

.Étapes
. Dans le widget *Inventaire*, sélectionnez *Systèmes* pour afficher les informations système de toutes les plateformes ou sélectionnez le type de plateforme, puis sélectionnez *Systèmes* pour afficher les systèmes spécifiques à cette plateforme.
. Sélectionnez le nœud ou le cluster pour afficher des informations détaillées sur le système.
. Sélectionnez *Télécharger* pour télécharger le rapport *Inventory* afin de consulter les détails du système au format .xls.
. Sélectionnez *Télécharger* pour télécharger le rapport *Ansible Inventory* afin de consulter les détails du système aux formats .yml et .ini au niveau de la région ou du site.
+
Les fichiers Ansible Inventory peuvent être utilisés avec les fichiers Ansible PlayBook personnalisés pour modifier la configuration de l'infrastructure.





[[view-support-entitled-switch-details]]
== Afficher les détails du commutateur d'assistance

.Étapes
. Dans le widget *Inventaire*, sélectionnez *Commutateurs bénéficiant d'une assistance* pour afficher les informations relatives à tous les commutateurs bénéficiant d'une assistance.

