---
sidebar: sidebar 
permalink: view-firmware-update-recommendations.html 
keywords: upgrade advisor, firmware recommendations, storage firmware, sp bmc firmware, system files, security files 
summary: Consultez les recommandations de mise à jour du micrologiciel de stockage, du micrologiciel SP/BMC, des fichiers système et des fichiers de sécurité. 
---
= Consultez les recommandations de mise à jour du micrologiciel dans Digital Advisor
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les clients peuvent désormais gagner du temps et économiser des efforts en permettant à Control Tower de mettre automatiquement à jour leurs systèmes avec les dernières versions de micrologiciel, éliminant ainsi le besoin d'intervention manuelle ou de planification. Cette mise à jour réduit le risque de rencontrer des problèmes en raison de versions de firmware obsolètes ou incompatibles, garantissant des performances, une stabilité et une sécurité optimales du système.

Les clients recevront en temps opportun des notifications et des alertes concernant l'état des mises à jour de firmware, ainsi que des options d'activation des paramètres AutoSupport et de mise à jour automatique.

.Étapes
. Sur la page du tableau de bord, sélectionnez *Autres recommandations* dans le widget *Upgrade Advisor*.
. Sélectionnez *Afficher les recommandations* pour consulter la liste des recommandations.
. Dans la colonne *État de la mise à jour*, sélectionnez *Voir la progression* pour afficher les clusters qui sont éligibles à une mise à jour.
. En cas de problème, sélectionnez les liens correspondants pour consulter les étapes permettant de résoudre les problèmes.

