= Prise en charge des commutateurs autorisés
:allow-uri-read: 




=== Prise en charge des commutateurs autorisés

Vous pouvez désormais afficher des informations sur les commutateurs SAN Brocade Fibre Channel éligibles au support. Cela inclut des détails sur le modèle de commutateur, le numéro de série et l'état de l'assistance. link:https://docs.netapp.com/us-en/active-iq/task_view_inventory_details.html["Apprenez à afficher les commutateurs de support autorisés"] .



=== Seuil pour les données RSS AutoSupport

La limite d'envoi récemment arrêté (RSS), dans le widget AutoSupport , a été étendue de 48 heures (2 jours) à 216 heures (9 jours) avant qu'un système ne soit signalé comme RSS.  Ceci est fait pour s'adapter aux plateformes comme StorageGRID qui n'envoient que des données AutoSupport hebdomadaires.



=== Section API obsolète dans le catalogue API de Digital Advisor

Une nouvelle section API obsolète est disponible dans le catalogue API de Digital Advisor .  Il répertorie les API dont l'obsolescence est prévue, ainsi que les calendriers d'obsolescence et les API alternatives.



=== Obsolescence des modules API de prévision de capacité V2 et de fin de support

Les modules API de prévision de capacité V2 et de fin de support sont prévus pour être obsolètes.  Pour accéder aux API obsolètes ou pour connaître les délais d'obsolescence et les API alternatives, accédez à *Services API -> Parcourir -> API obsolètes*.
